Testing github actions

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -10,9 +10,11 @@ jobs:
       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
       - name: Check out repository code
         uses: actions/checkout@v4
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
+      - name: Check ${{ github.actor }}.json exists
         run: |
-          ls ${{ github.workspace }}
+          |
+          if [ ! -f "${{ github.actor }}.json" ]; then
+            echo "Error: File ${{ github.actor }}.json not exist!"
+            exit 1
+          fi
       - run: echo "🍏 This job's status is ${{ job.status }}."
